#!/bin/sh		
#PBS -l nodes=1:ppn=8,mem=47gb 
#PBS -l walltime=500:00:00	
#PBS -j oe 
#PBS -m abe 
#PBS -V 
#PBS -M kjflynn@umich.edu
#PBS -q first
#PBS -A schloss_lab
echo "ncpus-2.pbs"
cat $PBS_NODEFILE
qstat -f $PBS_JOBID
cd $PBS_O_WORKDIR
NCPUS=`wc -l $PBS_NODEFILE | awk '{print $1}'`
/mnt/EXT/Schloss-data/bin/mothur gf_new_remove2.batch
echo "qsub working directory absolute is"
echo $PBS_O_WORKDIR
exit