#!/bin/sh		
#PBS -l nodes=1:ppn=8,mem=46gb 
#PBS -l walltime=476:00:00	
#PBS -l cput=9999:00:00 
#PBS -j oe 
#PBS -m abe 
#PBS -V 
#PBS -M kjflynn@umich.edu
#PBS -q first
#PBS -A schloss_lab
##PBS -W depend=afterok:1120319
echo "ncpus-2.pbs"
cat $PBS_NODEFILE
qstat -f $PBS_JOBID
cd $PBS_O_WORKDIR
NCPUS=`wc -l $PBS_NODEFILE | awk '{print $1}'`
/mnt/EXT/Schloss-data/bin/mothur gf_donors.batch 
echo "qsub working directory absolute is"
echo $PBS_O_WORKDIR
exit