#!/bin/sh		
#PBS -l nodes=1:ppn=2,mem=47gb 
#PBS -l walltime=500:00:00	
#PBS -j oe 
#PBS -m abe 
#PBS -V 
#PBS -M kjflynn@umich.edu
#PBS -q first
#PBS -A schloss_lab
echo "ncpus-2.pbs"
cat $PBS_NODEFILE
qstat -f $PBS_JOBID
cd $PBS_O_WORKDIR
NCPUS=`wc -l $PBS_NODEFILE | awk '{print $1}'`
/mnt/EXT/Schloss-data/bin/mothur "#cluster.split(fasta=gf_new.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.pick.fasta, count=gf_new.trim.contigs.good.unique.good.filter.unique.precluster.denovo.uchime.pick.pick.pick.count_table, taxonomy=gf_new.trim.contigs.good.unique.good.filter.unique.precluster.pick.pds.wang.pick.pick.taxonomy, splitmethod=classify, taxlevel=4, cutoff=0.15, processors=2, cluster=F)"
echo "qsub working directory absolute is"
echo $PBS_O_WORKDIR
exit