---
title: "humanCdGF_disease_severity"
author: "Nicholas Lesniak"
date: "January 11, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message=FALSE, fig.width=7, fig.height=8)
```

```{r setup environment}
pack_used <- c('tidyr','ggplot2','dplyr', 'knitr')
for (dep in pack_used){
  if (dep %in% installed.packages()[,"Package"] == FALSE){
    install.packages(as.character(dep), repos = 'http://cran.us.r-project.org', 
                     quiet=TRUE);
  }
  library(dep, verbose=FALSE, character.only=TRUE)
}
```

```{r process data, include=FALSE}
meta_file   <- '~/Documents/Github/Schubert_humanCdGF_XXXX_2016/data/process/human_CdGF_metadata.txt'
shared_file <- '~/Documents/Github/Schubert_humanCdGF_XXXX_2016/data/process/human_CdGF.an.unique_list.0.03.subsample.shared'
tax_file <- '~/Documents/Github/Schubert_humanCdGF_XXXX_2016/data/process/gf_new.an.taxonomy'
tax_function <- '~/Documents/Github/Schubert_humanCdGF_XXXX_2016/code/tax_level.R'

# read in files
meta_file   <- read.table(meta_file, sep = '\t', header = T, row.names = 'sample_id')
shared_file <- read.table(shared_file, sep = '\t', header = T, row.names = 'sample_id')
tax_file <- read.table(tax_file, sep = '\t', header = T, row.names = 'OTU')
source(tax_function)

# select only mice with 431 cdiff
meta_file <- meta_file[meta_file$cdiff_strain == '431', ]

# subset shared
#Create df with relative abundances
stool_shared <- shared_file[rownames(meta_file[meta_file$day %in% 0, ]) ,]
# use %in% instead of == because to ignore NA
# rename day 0 community rows by mouse id - since meta rows have day in row names, use mouse id for both
rownames(stool_shared) <- meta_file$mouse_id[rownames(meta_file) %in% 
                                               rownames(stool_shared) ]
rel_abund_stool <- 100 * stool_shared / unique(apply(stool_shared, 1, sum))
#Create vector of OTUs with median abundances >1%
OTUs_stool_0_01 <- apply(rel_abund_stool, 2, max) > 1
#df of OTUs with abundances >1% - by cage and inoculum
rel_abund_stool <- rel_abund_stool[ ,OTUs_stool_0_01]
OTU_list <- colnames(rel_abund_stool)
```

```{r Fig_2, fig.width=13, fig.height=7}

# Weight loss  
meta_file %>% 
  filter(day %in% c(0:10), !is.na(percent_weightLoss) ) %>%
  filter(!cage_id == 'NP1') %>% 
  select(mouse_id, day, Early_Euth, percent_weightLoss, cage_id) %>% 
  ggplot(aes(x = factor(day), y = percent_weightLoss, color = factor(Early_Euth))) + 
        geom_jitter(width = 0.3, alpha = 0.1) + 
        scale_color_manual(values = c('black', 'red'), breaks=c("FALSE", "TRUE"),
                           labels=c("Persistent", "Severe")) +
        stat_summary(fun.y=median, geom="line", aes(group = Early_Euth)) +
        labs(x = 'Day', y = ' Percent Relative to Day 0', title = 'Weight Loss') +
          stat_summary(fun.data = 'median_hilow', fun.args = (conf.int=0.5)) +
        theme_bw() +
        theme(legend.justification=c(1,0), legend.position=c(1,0.1), 
              legend.title=element_blank())


# C. Diff CFU
meta_file %>% 
  filter(day %in% c(0:10), !is.na(log_cfu) ) %>%
  filter(!cage_id == 'NP1') %>% 
  select(mouse_id, day, Early_Euth, log_cfu, cage_id) %>% 
  ggplot(aes(x = factor(day), y = log_cfu, color = factor(Early_Euth))) + 
        geom_jitter(width = 0.3, alpha = 0.2) + 
        scale_color_manual(values = c('black', 'red'), breaks=c("FALSE", "TRUE"),
                           labels=c("Persistent", "Severe")) +
        stat_summary(fun.y=median, geom="line", aes(group = Early_Euth)) +
        labs(x = 'Day', y = ' CFU (log10)', title = 'C. Difficile Colonization') +
        theme(legend.justification=c(1,0), legend.position=c(1,0.2), 
                  legend.title=element_blank()) +
        stat_summary(fun.data = 'median_hilow', fun.args = (conf.int=0.5)) + 
        theme_bw() +
        theme(legend.justification=c(1,0), legend.position=c(1,0.2), 
              legend.title=element_blank())


```


Points are median of Disease Severity Group and lines are IQR