---
title: "Predict Disease Outcome by Community Structures"
author: "Nicholas Lesniak"
date: "July 13, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, message=FALSE}
pack_used <- c('randomForest','miscTools','ggplot2','reshape2', 'pROC')
for (dep in pack_used){
  if (dep %in% installed.packages()[,"Package"] == FALSE){
    install.packages(as.character(dep), quiet=TRUE);
  }
  library(dep, verbose=FALSE, character.only=TRUE)
}
```

```{r}
setwd("~/Documents/Github/Schubert_humanCdGF_XXXX_2016")

# read in files
meta_file   <- read.table('data/process/human_CdGF_metadata.txt', sep = '\t',
                        header = T, row.names = 'group')
shared_file <- read.table('data/process/human_CdGF.an.unique_list.0.03.subsample.shared',
                          sep='\t',header = T, row.names='Group')

# add log transformed CFU
meta_file$log_cfu <- log10(meta_file$cdiff_cfu + 1)
# remove cecum samples
meta_file <- meta_file[! meta_file$sample_type == 'cecum', ]

# subset shared
#Create df with relative abundances
stool_shared <- shared_file[rownames(meta_file[meta_file$day %in% 0, ]) ,]
# use %in% instead of == because to ignore NA
# rename day 0 communities by mouse id
rownames(stool_shared) <- meta_file$Mouse_ID[rownames(meta_file) %in% 
                                               rownames(stool_shared) ]
rel_abund_stool <- 100 * stool_shared / unique(apply(stool_shared, 1, sum))
#Create vector of OTUs with median abundances >1%
OTUs_stool_0_01 <- apply(rel_abund_stool, 2, max) > 1
#df of OTUs with abundances >1% - by cage and inoculum
rel_abund_stool <- rel_abund_stool[ ,OTUs_stool_0_01]
OTU_list <- colnames(rel_abund_stool)

#random forest regression model to determine Day 0 OTU correlated with increased CFU
seed <- 18
n_trees <- 2000
set.seed(seed)

#log_cfu_obs <- meta_file[meta_file$day %in% c(0:10), c('Mouse_ID', 'day', 'log_cfu') ]
#log_cfu_obs$predict <- NA
#log_cfu_obs[log_cfu_obs$day==2, ] <- predict(RF, rel_abund_stool)

importance_df <- data.frame(matrix(nrow = length(OTU_list), 
                                   ncol = max(meta_file$day, na.rm = T)),
                            row.names = OTU_list)
rsq_df <- data.frame(matrix(nrow = 1, ncol = max(meta_file$day, na.rm = T)),
                         row.names = 'RSQ')
mse_df <- data.frame(matrix(nrow = 1, ncol = max(meta_file$day, na.rm = T)),
                         row.names = 'MSE')
prediction_df <- data.frame(matrix(nrow = 0, ncol = 4))

for (i in 1:10){
  predict_all_df <- merge(meta_file[meta_file$day==i, c('Mouse_ID', 'day' , 'log_cfu') ],
                    rel_abund_stool, by='Mouse_ID', by.y='row.names', all.y = T)
  predict_df <- predict_all_df[,! colnames(predict_all_df) %in% 'day']
  predict_df <- predict_df[ ,!(colnames(predict_df) %in% "Mouse_ID")]
  RF <- randomForest(log_cfu ~ ., data = predict_df[!is.na(predict_df$log_cfu), ],
                   importance = TRUE, ntree = n_trees)
  rsq_df[i] <- RF$rsq[length(RF$rsq)]
  mse_df[i] <- RF$mse[length(RF$mse)]

  # sort the features by their effect on % increase in the standard error
  importance_df[ , i] <- importance(RF)[,1]
  colnames(importance_df)[i] <- paste('day', i, 'importance', sep = '_')
# fit the model back on the datar and tack it to the end of the counts file
  random_forest_output <- cbind(predict_all_df[!is.na(predict_all_df$log_cfu), c('day','log_cfu')],
                              RF$predicted)
  colnames(random_forest_output) <- c('day', 'observed', 'predicted')
  prediction_df <- rbind(prediction_df, random_forest_output)  
}

ggplot(data = prediction_df, aes(x=observed, y=predicted)) + geom_point() + 
        facet_wrap( ~ day, nrow = 2) + 
        labs(title = 'Random Forest Prediction of C Diff CFU dpi from Day 0 Community',
        x= 'Observed CFU (log10)', y = 'Predicted CFU (log10)')

rsq_df <- t(rsq_df)
rsq_df <- as.data.frame(cbind(rsq_df, day = c(1:10)))
ggplot(data = rsq_df, aes(x = factor(day), y = RSQ)) + geom_point() + theme_bw() +
        labs(title = 'Variation Explained by Day of C Diff CFU dpi from Day 0 Community',
        x= 'Day', y = 'Variance Explained')

mse_df <- t(mse_df)
mse_df <- as.data.frame(cbind(mse_df, day = c(1:10)))
ggplot(data = mse_df, aes(x = factor(day), y = MSE)) + geom_point() + theme_bw() +
        labs(title = 'Variation Explained by Day of C Diff CFU dpi from Day 0 Community',
        x= 'Day', y = 'Variance Explained')

n_important <- 20
median_importance <- names(head(sort((apply(importance_df,1, median)), decreasing = T), n_important))
med_import_df <- melt(cbind(rownames(importance_df), importance_df)[median_importance, ])
colnames(med_import_df) <- c('OTU', 'Day', 'Importance')
ggplot(data = med_import_df, aes(x = factor(Day), y = Importance)) + facet_wrap( ~ OTU, nrow = 2) +
        geom_point() + scale_x_discrete(labels = c(1:10)) +
        labs(title = 'OTU Importance in Prediction of C Diff CFU dpi from Day 0 Community\n (Top 20 Median OTUs)',
        x= 'Day', y = '% Increase in MSE') + theme_bw()

#let's plot the top 12 features
#n_features <- 12
#importance_subset <- importance_sorted[1:n_features]
# let's get Rsq for the subset
#rf_partial <- randomForest(log_cfu ~ ., data=predict_df[!is.na(predict_df$log_cfu),
#                            c( 'log_cfu', names(importance_sorted)[1:n_features])], 
#                           importance=TRUE, ntree=n_trees)
# write(paste("partial", n_features, rf_partial$rsq[n_trees], "\t"), file="data/process/random_forest.data", append=T)
```

##Can we predict the endpoint C. difficile CFU with the community structure at Day 0?
Endpoint has data from Day 2,3,10 - might be misleading since contains CFU from different data points
     
```{r}

CFU_euth <- merge(meta_file[meta_file$day==meta_file$Euthanized, c('Mouse_ID', 'log_cfu') ],
                    rel_abund_stool, by='Mouse_ID', by.y='row.names', all.y = T)
CFU_euth <- CFU_euth[ ,!(colnames(CFU_euth) %in% "Mouse_ID")]

RF_CFU_day_euth <- randomForest(log_cfu ~ ., data = CFU_euth[!is.na(CFU_euth$log_cfu), ],
                   importance = TRUE, ntree = n_trees)
rsq_day_euth <- round(RF_CFU_day_euth$rsq[length(RF_CFU_day_euth$rsq)], 2)
mse_day_euth <- round(RF_CFU_day_euth$mse[length(RF_CFU_day_euth$mse)], 2)
# sort the features by their effect on % increase in the standard error
importance_day_euth <- importance(RF_CFU_day_euth)[,1]
# fit the model back on the datar and tack it to the end of the counts file
rf_predict_cfu_output <- cbind(CFU_euth[!is.na(CFU_euth$log_cfu), 'log_cfu'], data.frame(RF_CFU_day_euth$predicted))
colnames(rf_predict_cfu_output) <- c('observed', 'predicted')

ggplot(data = rf_predict_cfu_output, aes(x=observed, y=predicted)) + geom_point() + 
        labs(x= 'Observed CFU (log10)', y = 'Predicted CFU (log10)') + theme_bw() + 
        ggtitle("Random Forest Prediction of C Diff CFU on Day Euthanized from Day 0 Community") +
        annotate('text', x=0.15*(max(rf_predict_cfu_output$observed)), y=0.95*(max(rf_predict_cfu_output$predicted)), 
                 label=paste('R^2 = ', rsq_day_euth,'\nMSE = ', mse_day_euth, sep = ''))

top_important_OTU <- data.frame(head(sort(importance_day_euth, decreasing = T), n_important))
colnames(top_important_OTU) <- 'Importance'
top_important_OTU$OTU <- rownames(top_important_OTU)

ggplot(data = top_important_OTU, aes(x = factor(OTU), y = Importance)) + 
        geom_point() + scale_x_discrete(limits = rev(top_important_OTU$OTU)) +
        labs(title = 'OTU Importance in Prediction of C Diff CFU dpi from Day 0 Community',
        x= '', y = '% Increase in MSE') + theme_bw() + coord_flip()
```


***

##Can we predict moribundity with the community structure at Day 0?
```{r}
##Fix to be categorical, and not regression
Predict_early_euth_df <- data.frame(Euth_Early = ifelse(meta_file[meta_file$day %in% 0,
                                                                  'Euthanized'] %in% 10,
                                                        'No','Yes'), 
                                    row.names = meta_file[meta_file$day %in% 0, 'Mouse_ID'])
Predict_early_euth_df <- merge(Predict_early_euth_df, rel_abund_stool, by='row.names')
Predict_early_euth_df <- Predict_early_euth_df[,!(colnames(Predict_early_euth_df) %in% "Row.names")]
rf_early_euth <- randomForest(as.factor(Euth_Early) ~ ., data = Predict_early_euth_df, 
                              importance = TRUE, ntree = n_trees)
# write(paste("binary", ncol(rel_abund_stool), rf_early_euth$err.rate[n_trees], "\t"), file="data/process/random_forest.data", append=T)
#varImpPlot(rf_early_euth)
#prediction_euth <- as.numeric(predict(rf_early_euth, Predict_early_euth_df[,-1]))
#ROC_euth <- roc(as.numeric(Predict_early_euth_df$Euth_Early), prediction_euth)
#plot(ROC_euth)
```


***

##Does Day Community structure predict the each day C. difficile CFU?

RF all mice/days together
RF cfu vs community by day
