#!/bin/sh		
#PBS -l nodes=1:ppn=1,mem=100gb 
#PBS -l walltime=500:00:00	
#PBS -j oe 
#PBS -m abe 
#PBS -V 
#PBS -M kjflynn@umich.edu
#PBS -q first
#PBS -A schloss_lab
echo "ncpus-2.pbs"
cat $PBS_NODEFILE
qstat -f $PBS_JOBID
cd $PBS_O_WORKDIR
NCPUS=`wc -l $PBS_NODEFILE | awk '{print $1}'`
/mnt/EXT/Schloss-data/bin/mothur "#cluster.split(file=gf_all.trim.contigs.good.unique.good.filter.unique.precluster.pick.pick.pick.file, processors=1)"
echo "qsub working directory absolute is"
echo $PBS_O_WORKDIR
exit